---
- name: RPM Deploy saslauthd configuration
  template: src=saslauthd-rpm dest=/etc/sysconfig/saslauthd backup=yes
  notify: 
   - Restart saslauthd
  when: ansible_os_family == "RedHat"
  tags: sasl

- name: DEB Deploy saslauthd configuration
  template: src=saslauthd-deb dest=/etc/default/saslauthd backup=yes
  notify: 
   - Restart saslauthd
  when: ansible_os_family == "Debian"
  tags: sasl

- name: Deploy SASL configuration
  template: src={{ item }} dest=/etc backup=yes
  with_items:
   - pam_ldap_obm.conf
   - saslauthd.conf
  notify: 
   - Restart saslauthd
  tags: sasl
