---
- name: Merge PostgreSQL configuration files
  assemble: src={{ datadir }}/pg_hba.d dest={{ datadir }}/pg_hba.conf backup=yes
  delegate_to: "{{ item }}"
  with_items: groups.databaseservers
  notify: 
    - Reload Postgres
  tags:
   - postgres-common
   - pgperms

- name: Reload Postgres
  service: name=postgresql state=reloaded
  delegate_to: "{{ groups['dbmaster'][0] }}"
  tags:
   - postgres-common
   - pgperms

- name: Restart Postgres
  service: name=postgresql state=restarted
  delegate_to: "{{ groups['dbmaster'][0] }}"
  tags:
   - postgres-common
   - pgperms
