---
# Fix jetty6 init script (refers http://ci-obm.linagora.com/jira/browse/OBMFULL-5592)
- name: Fix jetty6 init script
  lineinfile: >
   line="	exit $?"
   dest=/etc/init.d/jetty6
   insertafter=".*status -p.*"
  when: major_version | version_compare('3.0', '<')
  notify: 
      - Restart OPush2
  tags: opush

- name: Deploy Opush main configuration
  template: src=opush.ini dest=/etc/opush/opush.ini mode=0644 backup=yes
  tags: opush

- name: Deploy Opush LDAP configuration
  template: src=ldap_conf.ini dest=/etc/opush/ldap_conf.ini mode=0644 backup=yes
  tags: opush

- name: Deploy Opush Logback configuration
  copy: src=logback.xml dest=/etc/opush/logback.xml mode=0644 backup=yes
  notify: 
      - Restart OPush2
      - Restart OPush3
  tags: opush

- name: Deploy Opush Cassandra configuration
  template: src=cassandra.ini dest=/etc/opush/cassandra.ini mode=0644 backup=yes
  when: major_version | version_compare('3.0', '>=')
  notify:
      - Restart OPush3
  tags: opush

- name: Cassandra schema initialization
  command: sshpass -p 'admin' ssh -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no -p 5665 -l admin0 localhost 'schema install'
  when: version | version_compare('3.1.2', '>=')
  notify:
      - Restart OPush3
  tags: opush

- name: Start Opush3
  service: name=opush enabled=yes state=started
  when: major_version | version_compare('3.0', '>=')
  tags: opush  
