---
#- name: Deploy default hosts file
#  copy: src=hosts dest=/etc/hosts
#  tags:
#      - common
#      - hosts

- name: Remove unneeded line from hosts file
  lineinfile: >
   regexp="127\.0\.0\.1*localdomain4"
   dest=/etc/hosts
   state=absent
  tags:
      - common
      - hosts

- name: Add host name to hosts file
  lineinfile: >
   line="127.0.0.1 {{ inventory_hostname }} {{ ansible_hostname }} localhost.localdomain localhost"
   regexp="127\.0\.0\.1*"
   dest=/etc/hosts
   insertafter=BOF
  tags:
      - common
      - hosts

- name: Cleanup hosts file if needed
  lineinfile: >
   regexp=".*{{ item }}"
   dest=/etc/hosts
   state=absent
  with_items:
   - mirror.centos.org
   - download.fedoraproject.org
   - rpm.obm.org
   - packages.obm.org
   - yum.postgresql.org
  when: mode == "internet"
  tags:
      - common
      - hosts
